# Generated by Django 5.2.16 on 2026-07-23 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_code', models.CharField(max_length=8, unique=True, verbose_name='DART 고유번호')),
                ('stock_code', models.CharField(max_length=6, unique=True, verbose_name='종목코드')),
                ('name', models.CharField(max_length=100, verbose_name='기업명')),
                ('sub_category', models.CharField(blank=True, max_length=50, verbose_name='서브 카테고리')),
                ('is_active', models.BooleanField(default=True, verbose_name='추적 여부')),
            ],
            options={
                'verbose_name': '기업',
                'verbose_name_plural': '기업',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='섹터명')),
                ('slug', models.SlugField(unique=True, verbose_name='슬러그')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '섹터',
                'verbose_name_plural': '섹터',
            },
        ),
        migrations.CreateModel(
            name='Disclosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcept_no', models.CharField(max_length=14, unique=True, verbose_name='접수번호')),
                ('report_name', models.CharField(max_length=300, verbose_name='공시 제목')),
                ('disclosure_type', models.CharField(blank=True, max_length=50, verbose_name='공시 유형')),
                ('filed_at', models.DateField(verbose_name='접수일자')),
                ('dart_url', models.URLField(max_length=300, verbose_name='원문 링크')),
                ('raw_fetched', models.BooleanField(default=False, verbose_name='원문 확보 여부')),
                ('raw_content', models.TextField(blank=True, verbose_name='원문 본문(전처리)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='수집 시각')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclosures', to='disclosures.company', verbose_name='기업')),
            ],
            options={
                'verbose_name': '공시',
                'verbose_name_plural': '공시',
                'ordering': ['-filed_at', '-rcept_no'],
            },
        ),
        migrations.CreateModel(
            name='DisclosureSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_line', models.CharField(max_length=200, verbose_name='한 줄 요약')),
                ('easy_explanation', models.TextField(verbose_name='쉬운 설명')),
                ('why_important', models.TextField(verbose_name='왜 중요한가')),
                ('importance', models.CharField(choices=[('high', '높음'), ('medium', '보통'), ('low', '낮음')], default='medium', max_length=10, verbose_name='중요도')),
                ('model_name', models.CharField(blank=True, max_length=50, verbose_name='사용 LLM')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='검수 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('disclosure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='disclosures.disclosure', verbose_name='공시')),
            ],
            options={
                'verbose_name': 'AI 요약',
                'verbose_name_plural': 'AI 요약',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='disclosures.sector', verbose_name='섹터'),
        ),
        migrations.AddIndex(
            model_name='disclosure',
            index=models.Index(fields=['company', '-filed_at'], name='disclosures_company_5ac37d_idx'),
        ),
    ]
