# Generated by Django 5.2.16 on 2026-07-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclosures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosure',
            name='exclusion_reason',
            field=models.CharField(blank=True, choices=[('blacklist', '정형 반복 공시(제목 블랙리스트)'), ('excluded_type', '요약 가치 낮은 공시유형')], default='', max_length=20, verbose_name='제외 사유'),
        ),
        migrations.AddField(
            model_name='disclosure',
            name='selection_state',
            field=models.CharField(choices=[('pending', '미판정'), ('target', '요약 대상'), ('excluded', '제외')], default='pending', max_length=10, verbose_name='선별 상태'),
        ),
        migrations.AddIndex(
            model_name='disclosure',
            index=models.Index(fields=['selection_state', 'raw_fetched'], name='disclosures_selecti_c7834b_idx'),
        ),
    ]
