# Generated by Django 5.2.16 on 2026-07-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclosures', '0002_disclosure_exclusion_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosuresummary',
            name='evidence',
            field=models.JSONField(blank=True, default=list, verbose_name='원문 근거'),
        ),
        migrations.AddField(
            model_name='disclosuresummary',
            name='review_warnings',
            field=models.JSONField(blank=True, default=list, verbose_name='자동 검증 경고'),
        ),
    ]
