# Generated by Django 5.2.16 on 2026-08-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclosures', '0003_disclosuresummary_evidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disclosure',
            name='exclusion_reason',
            field=models.CharField(blank=True, choices=[('blacklist', '정형 반복 공시(제목 블랙리스트)'), ('excluded_type', '요약 가치 낮은 공시유형'), ('reference_doc', '요약 부적합 대형 참고문서')], default='', max_length=20, verbose_name='제외 사유'),
        ),
    ]
