# Generated by Django 5.2.16 on 2026-08-11 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclosures', '0004_alter_disclosure_exclusion_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosuresummary',
            name='edited_by_human',
            field=models.BooleanField(default=False, verbose_name='사람 수정 여부'),
        ),
        migrations.AddField(
            model_name='disclosuresummary',
            name='hidden_reason',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='숨김 사유'),
        ),
        migrations.AddField(
            model_name='disclosuresummary',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='노출 여부'),
        ),
        migrations.AddField(
            model_name='disclosuresummary',
            name='llm_original',
            field=models.JSONField(blank=True, default=dict, verbose_name='LLM 원본'),
        ),
        migrations.AddField(
            model_name='disclosuresummary',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='검수 시각'),
        ),
        migrations.AddField(
            model_name='disclosuresummary',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_summaries', to=settings.AUTH_USER_MODEL, verbose_name='검수자'),
        ),
    ]
