# Generated by Django 5.2.16 on 2026-08-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclosures', '0005_disclosuresummary_edited_by_human_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosure',
            name='review_category',
            field=models.CharField(blank=True, choices=[('capital', '자본구조 변동'), ('control', '지배구조·존속 지위'), ('distress', '부실·감사의견'), ('safety', '중대재해')], default='', max_length=20, verbose_name='검수 필수 유형'),
        ),
        migrations.AddField(
            model_name='disclosuresummary',
            name='hidden_by',
            field=models.CharField(blank=True, choices=[('auto', '자동 미게시(검증 실패)'), ('human', '검수자가 내림')], default='', max_length=10, verbose_name='미게시 주체'),
        ),
        migrations.AddField(
            model_name='disclosuresummary',
            name='regeneration_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='재생성 시도 횟수'),
        ),
        migrations.AddField(
            model_name='disclosuresummary',
            name='regeneration_history',
            field=models.JSONField(blank=True, default=list, verbose_name='재생성 이력'),
        ),
    ]
