# Generated by Django 5.2.16 on 2026-08-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclosures', '0006_disclosure_review_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosuresummary',
            name='prompt_version',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='프롬프트 버전'),
        ),
    ]
