# Generated by Django 5.2.16 on 2026-09-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclosures', '0007_disclosuresummary_prompt_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosure',
            name='raw_fetch_attempted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='원문 확보 마지막 시도'),
        ),
        migrations.AddField(
            model_name='disclosure',
            name='raw_fetch_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='원문 확보 시도 횟수'),
        ),
        migrations.AddField(
            model_name='disclosure',
            name='raw_fetch_error',
            field=models.CharField(blank=True, max_length=300, verbose_name='원문 확보 마지막 오류'),
        ),
    ]
