# Generated by Django 5.2.16 on 2026-09-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclosures', '0008_disclosure_raw_fetch_attempted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosure',
            name='summary_attempted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='요약 마지막 시도'),
        ),
        migrations.AddField(
            model_name='disclosure',
            name='summary_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='요약 시도 횟수'),
        ),
        migrations.AddField(
            model_name='disclosure',
            name='summary_error',
            field=models.CharField(blank=True, max_length=300, verbose_name='요약 마지막 오류'),
        ),
    ]
