# Generated by Django 5.2.16 on 2026-09-22 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclosures', '0009_disclosure_summary_attempted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListedCorp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_code', models.CharField(max_length=8, unique=True, verbose_name='DART 고유번호')),
                ('stock_code', models.CharField(max_length=6, unique=True, verbose_name='종목코드')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='기업명')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='명단 갱신 시각')),
            ],
            options={
                'verbose_name': '상장사 명단',
                'verbose_name_plural': '상장사 명단',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='backfill_attempted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마지막 백필 시도 시각'),
        ),
        migrations.AddField(
            model_name='company',
            name='backfill_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='백필 시도 횟수'),
        ),
        migrations.AddField(
            model_name='company',
            name='backfill_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='백필 요청 시각'),
        ),
        migrations.AddField(
            model_name='company',
            name='backfilled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='백필 완료 시각'),
        ),
        migrations.AddField(
            model_name='company',
            name='untracked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='추적 중단 시각'),
        ),
        migrations.CreateModel(
            name='WatchAddition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='추가 시각')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disclosures.company', verbose_name='기업')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_additions', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '관심 기업 추가 기록',
                'verbose_name_plural': '관심 기업 추가 기록',
            },
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='추가 시각')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='disclosures.company', verbose_name='기업')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '관심 기업',
                'verbose_name_plural': '관심 기업',
                'ordering': ['company__name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='unique_watch')],
            },
        ),
    ]
