# Generated by Django 5.2.16 on 2026-09-22 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclosures', '0011_stop_fixed_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosure',
            name='summary_requested_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='요약 요청 시각'),
        ),
        migrations.CreateModel(
            name='AiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='호출 시각')),
                ('model_name', models.CharField(max_length=50, verbose_name='모델')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name='입력 토큰')),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='출력 토큰')),
                ('cached_tokens', models.PositiveIntegerField(default=0, verbose_name='캐시 적중 토큰')),
                ('cost_usd', models.FloatField(verbose_name='추정 비용(USD)')),
                ('disclosure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usages', to='disclosures.disclosure', verbose_name='공시')),
            ],
            options={
                'verbose_name': 'AI 호출 비용',
                'verbose_name_plural': 'AI 호출 비용',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SummaryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='요청 시각')),
                ('disclosure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_requests', to='disclosures.disclosure', verbose_name='공시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_requests', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '요약 요청',
                'verbose_name_plural': '요약 요청',
                'constraints': [models.UniqueConstraint(fields=('user', 'disclosure'), name='unique_summary_request')],
            },
        ),
    ]
