"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# os.getenv의 기본값은 변수가 **없을 때만** 쓰인다. .env에 `DJANGO_SECRET_KEY=`처럼
# 빈 값으로 적혀 있으면 ''가 그대로 들어와 요청 처리 시점에
# ImproperlyConfigured('The SECRET_KEY setting must not be empty')로 죽는다.
# `or`로 받아 "없음"과 "빈 값"을 같게 취급한다.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY') or (
    'django-insecure-j=n_y4g%o=1sbh_^74!(0&ofpehp++-ty+aa&!2z-#%12b#($3'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = [h for h in os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',') if h]

# HTTPS 리버스 프록시(Caddy) 뒤에서 돌 때만 켜는 스위치.
# `not DEBUG`를 조건으로 쓰면 안 된다 — Django 테스트 러너가 DEBUG=False로 돌기 때문에
# 테스트 클라이언트(http)가 Secure 쿠키를 못 받아 로그인 관련 테스트가 깨진다.
BEHIND_HTTPS_PROXY = os.getenv('DJANGO_BEHIND_HTTPS_PROXY', 'false').lower() == 'true'

if BEHIND_HTTPS_PROXY:
    # Caddy가 붙여주는 헤더로 원 요청이 HTTPS였음을 인식한다.
    # 이 설정은 신뢰할 수 있는 프록시 뒤에서만 유효하다 — gunicorn을 외부에 직접
    # 노출하면 클라이언트가 헤더를 위조할 수 있으므로, 컨테이너 포트는 127.0.0.1에만 묶는다.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # HSTS(SECURE_HSTS_SECONDS)는 의도적으로 켜지 않는다. 브라우저가 정책을 캐시해
    # 문제가 생겨도 되돌리기 어렵다. 운영이 안정된 뒤 별도로 검토한다.
    # SECURE_SSL_REDIRECT도 불필요하다 — Caddy가 http를 https로 이미 돌린다.

# HTTPS 도메인에서 admin 폼을 제출하려면 Origin이 여기 등록되어 있어야 한다.
# 예: https://example.duckdns.org
CSRF_TRUSTED_ORIGINS = [
    o for o in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o
]

# DART OpenAPI (https://opendart.fss.or.kr/)
DART_API_KEY = os.getenv('DART_API_KEY', '')

# OpenAI API (https://developers.openai.com/) — 공시 AI 요약에 사용.
# 관리 명령/비동기 태스크에서만 호출한다. 사용자 요청 경로에서 직접 호출 금지(PLAN.md 12.1).
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'disclosures',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 정적 파일 서빙. SecurityMiddleware 바로 다음이어야 한다(whitenoise 공식 권장).
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 운영에서도 SQLite를 쓴다. 근거와 PostgreSQL 전환 트리거는 PLAN.md 9.2 참조.
# 컨테이너에서는 DB 파일이 마운트된 볼륨에 있어야 한다 — 이미지 안에 두면
# 재배포 때 요약이 통째로 사라진다.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.getenv('DJANGO_DB_PATH') or BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            # WAL: 읽기가 쓰기를 막지 않는다. 웹(읽기 전용)과 cron 파이프라인(쓰기)이
            # 같은 파일을 보는 구성이라 이게 있어야 조회가 잠기지 않는다.
            # journal_mode는 DB 파일에 저장되는 영구 속성이라 매 연결 실행해도 무해하다.
            'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;',
            # 쓰기 잠금 대기 시간. 기본 5초로는 요약 배치와 admin 저장이 겹칠 때 부족하다.
            'timeout': 20,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# collectstatic 산출물. whitenoise가 이 디렉터리를 서빙한다.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 파일명에 해시를 붙여 캐시를 무효화하는 저장소. collectstatic을 먼저 돌려야
# 동작하므로 기본값은 꺼둔다 — 켠 채로 테스트를 돌리면 매니페스트가 없어 깨진다.
# 컨테이너 이미지 빌드 시점에 켜고 collectstatic을 실행한다(Dockerfile).
if os.getenv('DJANGO_STATIC_MANIFEST', 'false').lower() == 'true':
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
